use std::str::FromStr;
use crate::ast::*;

grammar;

match {
    r"\s*" => {},
    r"//[^\n]*[\n]*" => {},
    r"/\*([^*]*\*+)+/" => {},
    _
}

pub Program: Program = <function_definition: FunctionDefinition> => Program {<>};

FunctionDefinition: FunctionDefinition = <function_type: FunctionType> <name: Identifier> "(" ")" <body: Block> => FunctionDefinition {<>};

FunctionType: FunctionType = "int" => FunctionType {};

Block: Block = "{" <statement: Statement> "}" => Block { statements: vec![statement] };

Statement: Statement = "return" <x: Expression> ";" => Statement { value: x };

Expression: Box<Expression> = {
    Term,
};

Term: Box<Expression> = {
    Factor,
};

Factor: Box<Expression> = {
    Unary,
};

Unary: Box<Expression> = {
    "+" <Unary> => Box::new(Expression::Unary(UnaryOperator::Plus, <>)),
    "-" <Unary> => Box::new(Expression::Unary(UnaryOperator::Minus, <>)),
    "!" <Unary> => Box::new(Expression::Unary(UnaryOperator::BooleanNot, <>)),
    "~" <Unary> => Box::new(Expression::Unary(UnaryOperator::BitNot, <>)),
    Primary,
};

Primary: Box<Expression> = {
    Number => Box::new(Expression::Number(<>)),
    "(" <Expression> ")",
};

Number: i32 = IntegerLiteral => <>;

Identifier: String = r"[_a-zA-Z][_a-zA-Z0-9]*" => <>.to_string();

IntegerLiteral: i32 = {
    r"[1-9][0-9]*" => i32::from_str(<>).unwrap(),
    r"0[xX][0-9a-fA-F]+" => i32::from_str_radix(&<>[2..], 16).unwrap(),
    r"0[0-7]*" => i32::from_str_radix(<>, 8).unwrap(),
    r"0[oO][0-7]+" => i32::from_str_radix(&<>[2..], 8).unwrap(),
    r"0[bB][01]+" => i32::from_str_radix(&<>[2..], 2).unwrap(),
}
