use std::str::FromStr;
use crate::ast::*;

grammar;

match {
    r"\s*" => {},
    r"//[^\n]*[\n]*" => {},
    r"/\*([^*]*\*+)+/" => {},
    _
}

pub Program: Program = <functions: FunctionDefinition+> => Program {<>};

FunctionDefinition: FunctionDefinition = <function_type: FunctionType> <name: Identifier> "(" <mut parameters: (<Parameter> ",")*> <last_parameter: Parameter?> ")" <body: Block> => {
    if let Some(last_parameter) = last_parameter {
        parameters.push(last_parameter);
    }
    FunctionDefinition {
        name,
        parameters,
        body,
    }
};

FunctionType: () = {
    "void",
    "int",
};

Parameter: Parameter = <parameter_type: BasicType> <name: Identifier> => Parameter {<>};

Block: Vec<Statement> = "{" <statement: BlockItem*> "}" => statement.concat();

BlockItem: Vec<Statement> = {
    Declaration => <>.into_iter().map(|d| Statement::Declaration(d)).collect(),
    Statement => vec![<>],
};

BasicType: BasicType = "int" => BasicType {};

Declaration: Vec<Declaration> = {
    ConstantDeclaration,
    VariableDeclaration,
};

ConstantDeclaration: Vec<Declaration> = "const" <constant_type: BasicType> <mut items: (<ConstantDefinition> ",")*> <last: ConstantDefinition> ";" => {
    items.push(last);
    items
        .into_iter()
        .map(|(name, value)| Declaration::Constant {
            constant_type: constant_type.clone(),
            name,
            value,
        })
        .collect()
};

ConstantDefinition: (String, Box<Expression>) = <Identifier> "=" <Expression> => (<>);

VariableDeclaration: Vec<Declaration> = <variable_type: BasicType> <mut items: (<VariableDefinition> ",")*> <last: VariableDefinition> ";" => {
    items.push(last);
    items
        .into_iter()
        .map(|(name, value)| Declaration::Variable {
            variable_type: variable_type.clone(),
            name,
            initial_value: value,
        })
        .collect()
};

VariableDefinition: (String, Option<Box<Expression>>) = Identifier ("=" <Expression>)? => (<>);

Statement: Statement = {
    OpenStatement,
    ClosedStatement,
};

OpenStatement: Statement = {
    "if" "(" <condition: Expression> ")" <then: Statement> => Statement::If { condition, then: Box::new(then), otherwise: None },
    "if" "(" <condition: Expression> ")" <then: ClosedStatement> "else" <otherwise: OpenStatement> => Statement::If { condition, then: Box::new(then), otherwise: Some(Box::new(otherwise)) },
    "while" "(" <condition: Expression> ")" <body: OpenStatement> => Statement::While { condition, body: Box::new(body) },
};

ClosedStatement: Statement = {
    <target: LValue> "=" <value: Expression> ";" => Statement::Assign {<>},
    <Expression> ";" => Statement::Expression(<>),
    ";" => Statement::Block(vec![]),
    <Block> => Statement::Block(<>),
    "if" "(" <condition: Expression> ")" <then: ClosedStatement> "else" <otherwise: ClosedStatement> => Statement::If { condition, then: Box::new(then), otherwise: Some(Box::new(otherwise)) },
    "while" "(" <condition: Expression> ")" <body: ClosedStatement> => Statement::While { condition, body: Box::new(body) },
    "break" ";" => Statement::Break,
    "continue" ";" => Statement::Continue,
    "return" <x: Expression> ";" => Statement::Return(x),
    "return" ";" => Statement::Return(Box::new(Expression::Number(0))),
};

Expression: Box<Expression> = LogicOr;

LogicOr: Box<Expression> = {
    LogicOr LogicOrOperator LogicAnd => Box::new(Expression::Binary(<>)),
    LogicAnd,
};

LogicOrOperator: BinaryOperator = {
    "||" => BinaryOperator::BooleanOr,
}

LogicAnd: Box<Expression> = {
    LogicAnd LogicAndOperator Equality => Box::new(Expression::Binary(<>)),
    Equality,
};

LogicAndOperator: BinaryOperator = {
    "&&" => BinaryOperator::BooleanAnd,
}

Equality: Box<Expression> = {
    Equality EqualityOperator Comparison => Box::new(Expression::Binary(<>)),
    Comparison,
};

EqualityOperator: BinaryOperator = {
    "==" => BinaryOperator::Equal,
    "!=" => BinaryOperator::NotEqual,
}

Comparison: Box<Expression> = {
    Comparison ComparisonOperator Term => Box::new(Expression::Binary(<>)),
    Term,
};

ComparisonOperator: BinaryOperator = {
    "<" => BinaryOperator::Less,
    "<=" => BinaryOperator::LessEqual,
    ">" => BinaryOperator::Greater,
    ">=" => BinaryOperator::GreaterEqual,
}

Term: Box<Expression> = {
    Term TermOperator Factor => Box::new(Expression::Binary(<>)),
    Factor,
};

TermOperator: BinaryOperator = {
    "+" => BinaryOperator::Plus,
    "-" => BinaryOperator::Minus,
}

Factor: Box<Expression> = {
    Factor FactorOperator Unary => Box::new(Expression::Binary(<>)),
    Unary,
};

FactorOperator: BinaryOperator = {
    "*" => BinaryOperator::Multiply,
    "/" => BinaryOperator::Divide,
    "%" => BinaryOperator::Modulo,
}

Unary: Box<Expression> = {
    UnaryOperator Unary => Box::new(Expression::Unary(<>)),
    <function_name: Identifier> "(" <mut arguments: (<Expression> ",")*> <last_argument: Expression?> ")" => {
        if let Some(last_argument) = last_argument {
            arguments.push(last_argument);
        }
        Box::new(Expression::Call {
            function_name,
            arguments: arguments.into_iter().map(|arg| *arg).collect(),
        })
    },
    Primary,
};

UnaryOperator: UnaryOperator = {
    "+" => UnaryOperator::Plus,
    "-" => UnaryOperator::Minus,
    "!" => UnaryOperator::BooleanNot,
    "~" => UnaryOperator::BitNot,
}

Primary: Box<Expression> = {
    LValue,
    Number => Box::new(Expression::Number(<>)),
    "(" <Expression> ")",
};

LValue: Box<Expression> = {
    Identifier => Box::new(Expression::Variable(<>)),
};

Number: i32 = IntegerLiteral => <>;

Identifier: String = r"[_a-zA-Z][_a-zA-Z0-9]*" => <>.to_string();

IntegerLiteral: i32 = {
    r"[1-9][0-9]*" => i32::from_str(<>).unwrap(),
    r"0[xX][0-9a-fA-F]+" => i32::from_str_radix(&<>[2..], 16).unwrap(),
    r"0[0-7]*" => i32::from_str_radix(<>, 8).unwrap(),
    r"0[oO][0-7]+" => i32::from_str_radix(&<>[2..], 8).unwrap(),
    r"0[bB][01]+" => i32::from_str_radix(&<>[2..], 2).unwrap(),
}
