use std::str::FromStr;
use crate::ast::*;

grammar;

match {
    r"\s*" => {},
    r"//[^\n]*[\n]*" => {},
    r"/\*([^*]*\*+)+/" => {},
    _
}

pub Program: Program = <items: TopLevelItem*> => {
    let mut program = Program {
        declarations: vec![],
        functions: vec![],
    };
    for item in items {
        match item {
            TopLevelItem::Declaration(declaration) => {
                program.declarations.extend(declaration);
            }
            TopLevelItem::Function(function) => {
                program.functions.push(function);
            }
        }
    }
    program
};

TopLevelItem: TopLevelItem = {
    Declaration => TopLevelItem::Declaration(<>),
    FunctionDefinition => TopLevelItem::Function(<>),
};

FunctionDefinition: FunctionDefinition = <function_type: BasicType> <name: Identifier> "(" <mut parameters: (<Parameter> ",")*> <last_parameter: Parameter?> ")" <body: Block> => {
    if let Some(last_parameter) = last_parameter {
        parameters.push(last_parameter);
    }
    FunctionDefinition {
        name,
        parameters,
        body,
    }
};

Parameter: Parameter = BasicType <name: Identifier> <parameter_type: Type> => Parameter {<>};

Block: Vec<Statement> = "{" <statement: BlockItem*> "}" => statement.concat();

BlockItem: Vec<Statement> = {
    Declaration => <>.into_iter().map(|d| Statement::Declaration(d)).collect(),
    Statement => vec![<>],
};

Type: Type = <dimensions: Dimension*> => Type {<>};

BasicType: () = {
    "void",
    "int",
};

Dimension: Expression = "[" <Expression?> "]" => match <> {
    Some(expression) => *expression,
    None => Expression::Number(0),
};

Declaration: Vec<Declaration> = <const_keyword: "const"?> BasicType <mut items: (<VariableDefinition> ",")*> <last: VariableDefinition> ";" => {
    items.push(last);
    items
        .into_iter()
        .map(|variable_definition| match (const_keyword, variable_definition) {
            (Some(_), (name, Type { dimensions }, Some(InitializerListItem::Value(value)))) if dimensions.is_empty() => Declaration::Constant {
                name,
                value,
            },
            (_, (name, variable_type, initial_value)) => Declaration::Variable {
                variable_type,
                name,
                initial_value,
            },
        })
        .collect()
};

VariableDefinition: (String, Type, Option<InitializerListItem>) = Identifier Type ("=" <InitializerListItem>)? => (<>);

InitializerList: Vec<InitializerListItem> = "{" <mut items: (<InitializerListItem> ",")*> <last: InitializerListItem?> "}" => {
    if let Some(last) = last {
        items.push(last);
    }
    items
};

InitializerListItem: InitializerListItem = {
    Expression => InitializerListItem::Value(<>),
    InitializerList => InitializerListItem::List(<>),
};

Statement: Statement = {
    OpenStatement,
    ClosedStatement,
};

OpenStatement: Statement = {
    "if" "(" <condition: Expression> ")" <then: Statement> => Statement::If { condition, then: Box::new(then), otherwise: None },
    "if" "(" <condition: Expression> ")" <then: ClosedStatement> "else" <otherwise: OpenStatement> => Statement::If { condition, then: Box::new(then), otherwise: Some(Box::new(otherwise)) },
    "while" "(" <condition: Expression> ")" <body: OpenStatement> => Statement::While { condition, body: Box::new(body) },
};

ClosedStatement: Statement = {
    <target: LValue> "=" <value: Expression> ";" => Statement::Assign {<>},
    <Expression> ";" => Statement::Expression(<>),
    ";" => Statement::Block(vec![]),
    <Block> => Statement::Block(<>),
    "if" "(" <condition: Expression> ")" <then: ClosedStatement> "else" <otherwise: ClosedStatement> => Statement::If { condition, then: Box::new(then), otherwise: Some(Box::new(otherwise)) },
    "while" "(" <condition: Expression> ")" <body: ClosedStatement> => Statement::While { condition, body: Box::new(body) },
    "break" ";" => Statement::Break,
    "continue" ";" => Statement::Continue,
    "return" <x: Expression> ";" => Statement::Return(x),
    "return" ";" => Statement::Return(Box::new(Expression::Number(0))),
};

Expression: Box<Expression> = LogicOr;

LogicOr: Box<Expression> = {
    LogicOr LogicOrOperator LogicAnd => Box::new(Expression::Binary(<>)),
    LogicAnd,
};

LogicOrOperator: BinaryOperator = {
    "||" => BinaryOperator::BooleanOr,
}

LogicAnd: Box<Expression> = {
    LogicAnd LogicAndOperator Equality => Box::new(Expression::Binary(<>)),
    Equality,
};

LogicAndOperator: BinaryOperator = {
    "&&" => BinaryOperator::BooleanAnd,
}

Equality: Box<Expression> = {
    Equality EqualityOperator Comparison => Box::new(Expression::Binary(<>)),
    Comparison,
};

EqualityOperator: BinaryOperator = {
    "==" => BinaryOperator::Equal,
    "!=" => BinaryOperator::NotEqual,
}

Comparison: Box<Expression> = {
    Comparison ComparisonOperator Term => Box::new(Expression::Binary(<>)),
    Term,
};

ComparisonOperator: BinaryOperator = {
    "<" => BinaryOperator::Less,
    "<=" => BinaryOperator::LessEqual,
    ">" => BinaryOperator::Greater,
    ">=" => BinaryOperator::GreaterEqual,
}

Term: Box<Expression> = {
    Term TermOperator Factor => Box::new(Expression::Binary(<>)),
    Factor,
};

TermOperator: BinaryOperator = {
    "+" => BinaryOperator::Plus,
    "-" => BinaryOperator::Minus,
}

Factor: Box<Expression> = {
    Factor FactorOperator Unary => Box::new(Expression::Binary(<>)),
    Unary,
};

FactorOperator: BinaryOperator = {
    "*" => BinaryOperator::Multiply,
    "/" => BinaryOperator::Divide,
    "%" => BinaryOperator::Modulo,
}

Unary: Box<Expression> = {
    UnaryOperator Unary => Box::new(Expression::Unary(<>)),
    <function_name: Identifier> "(" <mut arguments: (<Expression> ",")*> <last_argument: Expression?> ")" => {
        if let Some(last_argument) = last_argument {
            arguments.push(last_argument);
        }
        Box::new(Expression::Call {
            function_name,
            arguments: arguments.into_iter().map(|arg| *arg).collect(),
        })
    },
    Primary,
};

UnaryOperator: UnaryOperator = {
    "+" => UnaryOperator::Plus,
    "-" => UnaryOperator::Minus,
    "!" => UnaryOperator::BooleanNot,
    "~" => UnaryOperator::BitNot,
}

Primary: Box<Expression> = {
    LValue,
    Number => Box::new(Expression::Number(<>)),
    "(" <Expression> ")",
};

LValue: Box<Expression> = <variable_name: Identifier> <indices: Dimension*> => {
    let mut expression = Box::new(Expression::Variable(variable_name));
    for index in indices {
        expression = Box::new(Expression::Element(expression, Box::new(index)));
    }
    expression
};

Number: i32 = IntegerLiteral => <>;

Identifier: String = r"[_a-zA-Z][_a-zA-Z0-9]*" => <>.to_string();

IntegerLiteral: i32 = {
    r"[1-9][0-9]*" => i32::from_str(<>).unwrap(),
    r"0[xX][0-9a-fA-F]+" => i32::from_str_radix(&<>[2..], 16).unwrap(),
    r"0[0-7]*" => i32::from_str_radix(<>, 8).unwrap(),
    r"0[oO][0-7]+" => i32::from_str_radix(&<>[2..], 8).unwrap(),
    r"0[bB][01]+" => i32::from_str_radix(&<>[2..], 2).unwrap(),
}
